version: '3'

services:
  dev:
    image: "node:alpine"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    working_dir: /code
    command: ./bin/dev.sh
    environment:
      - NODE_ENV=dev
    networks:
      - back-tier
    restart: always


networks:
  back-tier:
    driver: bridge
